version: '3.8'

services:
  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/my_database  # URL de conexión a la base de datos MySQL
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: userpassword

#  server:
#    image: tupfrcutn/elecciones-2023:1.0.0
#    ports:
#      - "8081:8081"
#    networks:
#      - network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  network:

volumes:
  mysql-data:
